### ISSUE TITLE
When destructuring with require statements httpsAgent and agent are null

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-https-agent#3]
Javascript copies primitives such as numbers, strings, and apparently null by value while functions and objects are by reference.

Hence this code:

```js
const {httpsAgent} = require('bedrock-https-agent');
```
assigns `null` to httpsAgent. While an event in `bedrock.init` sets `exports.agent` and `exports.httpsAgent` later on, because we copied by value and not by reference in this case `httpsAgent` will continue to be null if this require statement is evaluated before `bedrock.init`. The later is usually the case.

Suggestion:

- [ ] make `httpsAgent` a computed property, getter on an es6 class, or default to an empty object instead of null.

EDIT: it looks I might be wrong about how javascript copies: https://stackoverflow.com/questions/6605640/javascript-by-reference-vs-by-value

but regardless destructuring on `exports` is pretty common so our current pattern might be frustrating to some.

use an es6 class with `get` and `set` should solve these issues.

**Comment by mattcollier** [comment]
I'd like to see some improvement as well, but this is why you see `const {httpsAgent} = brHttpsAgent;` in code right before it is passed into axios or http-client.  That usage pattern is compatible with the implementation.

**Comment by dlongley** [comment]
This has been addressed.
